### ISSUE TITLE
JGRPP version support or some other error?

### ISSUE THREAD

**Issue by eirc** [aidansean/OpenTTD_surveyor#6]
Hello, is the JGRPP version of OpenTTD supported? I'm getting some error I think it cannot find the owner of some bridge with my savegame but I'm not 100% if it's JGRPP that's responsible for that or not.

Here's the full exception along with some context:
```
INFO:Surveyor:[2021-05-31 13:28:31.757651]  All done!
INFO:Surveyor:[2021-05-31 13:28:31.812244]  Min, max map height: 0, 255
INFO:Surveyor:[2021-05-31 13:28:31.890413]  Dimensions of tile size, image before resizing: 50, 25550 x 25550
INFO:Surveyor:[2021-05-31 13:28:31.890888]  Dimensions of tile size, image after resizing : 50, 25550 x 25550
INFO:Surveyor:[2021-05-31 13:28:32.190478]  Drawing tile backgrounds.
INFO:Surveyor:[2021-05-31 13:28:39.897068]  Drawing road tiles.
INFO:Surveyor:[2021-05-31 13:28:40.242632]  Drawing rail tiles.
INFO:Surveyor:[2021-05-31 13:28:45.233072]  Drawing station tiles.
INFO:Surveyor:[2021-05-31 13:28:47.840059]  Drawing tunnel mouth and bridge ramp tiles.
INFO:Surveyor:[2021-05-31 13:28:47.899509]  Drawing building tiles.
INFO:Surveyor:[2021-05-31 13:28:50.830704]  Drawing industry tiles.
INFO:Surveyor:[2021-05-31 13:28:52.405351]  Drawing water tiles.
INFO:Surveyor:[2021-05-31 13:28:57.646366]  Drawing road tiles.
INFO:Surveyor:[2021-05-31 13:28:57.756247]  Drawing tram tiles.
INFO:Surveyor:[2021-05-31 13:28:57.796677]  Drawing rail tiles.
INFO:Surveyor:[2021-05-31 13:29:01.166532]  Drawing rail signals.
INFO:Surveyor:[2021-05-31 13:29:01.260801]  Drawing bridges over tiles.
Traceback (most recent call last):
  File "/app/src/run.py", line 113, in <module>
Working with the following settings:
   save_file_path: /data/fureito.sav
 output_file_path: /data/fureito.png
 config_file_path: config/main.json
       image_mode: PNG
        tile_size: None
          verbose: True
show_progress_bar: False
        dark_mode: False
    main()
  File "/app/src/run.py", line 109, in main
    surveyor.save_image(output_file_path, image_mode)
  File "/app/src/surveyor.py", line 178, in save_image
    self.painter.save_image(image_file_path, filetype=filetype)
  File "/app/src/cairo_painter.py", line 2050, in save_image
    self.draw_bridges_over(all_tiles)
  File "/app/src/cairo_painter.py", line 1829, in draw_bridges_over
    self.draw_unknown_bridge_over(tiles, tile, tile.bridge - 1)
  File "/app/src/cairo_painter.py", line 1305, in draw_unknown_bridge_over
    self.draw_rail_bridge_over(tile, rotation, track_type, source_tile_owner)
  File "/app/src/cairo_painter.py", line 849, in draw_rail_bridge_over
    self.draw_bridge_over(tile, rotation, "rail", track_type, None, source_tile_owner)
  File "/app/src/cairo_painter.py", line 782, in draw_bridge_over
    self.draw_rail_line(
  File "/app/src/cairo_painter.py", line 452, in draw_rail_line
    inner_rgb = self.player_colors[owner]
TypeError: list indices must be integers or slices, not NoneType
```

Also attaching the savegame: [fureito.sav.zip](https://github.com/aidansean/OpenTTD_surveyor/files/6570304/fureito.sav.zip)

Edit: added more context to the log

**Comment by aidansean** [comment]
Thanks for the report and the save file! Unfortunately, the save file is not in a compatible format for the Surveyor tool to work. The chunks it expects to exist (MAPS, MAPT, MAPH, MAP0, MAP2, M3LO, M3HI, MAP5, MAPE, MAP7, MAP8) do not exist, so it attempts to parse bytes from the start of the file. As a result, the image that comes out is nonsense, and that's also why it can't find the owner of the bridge.

I've tried to open the file, but my version of OpenTTD (1.11.2) can't open the save file, so I can't offer any more help at the moment. Can you point me in the direction of the version of OpenTTD you're using, or save the file in save file format version 34? (The file you provided is version 35.)

I'll add a note on the repo to state that Surveyor supports save file formats up to version 34.

**Comment by eirc** [comment]
Hey, this is the patched version of OpenTTD I'm using: https://github.com/JGRennison/OpenTTD-patches, my understanding is they have updated it for 1.11.2 of the upstream (but I don't know how they do that, I just saw some of the features of 1.11 in the latest jgrpp).

About the save file versioning I think they just add one to the latest OpenTTD version in order to not allow the official client to open the fork's savegames since that would never work. But if the contents are totally different as you mention it's possible this will never work.

**Comment by eirc** [comment]
Ok, I commented out the bridge drawing and the script did work but I saw the mess it produced so now I understand :D
